#+OPTIONS:   H:2 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+TITLE: Reproducible Research Workshop
#+AUTHOR: Dylan Schwilk

May 13, 2015 12:30-4:30 PM, Biology 405

* Setup

The windows computers in room 405 will have software pre-installed.  If you want to bring your own laptop (recommended), please install the following software. 

** The Bash Shell
Bash is a commonly-used shell that gives you the power to do simple tasks more quickly.
*** Windows
	Install Git for Windows by download and running [[http://msysgit.github.io/][the installer]] this will provide you with both Git and Bash in the Git Bash program.
*** Mac OS X
The default shell in all versions of Mac OS X is bash, so no need to install anything.  You access bash from the Terminal (found in =/Applications/Utilities=).  You may want to keep Terminal in your dock for this workshop.
*** Linux
The default shell is usually =bash=, but if your machine is set up differently you can run it by opening a terminal and typing =bash=.  There is no need to install anything.
** Git
Git is a version control system that lets you track who made changes to what when and has options for easily updating a shared or public version of your code on [[https://github.com/][github.com]]. I recommend you go ahead now and obtain a github.com account. This is not necessary, but will allow you to store your repositories on github for collaboration.
*** Windows
Git should be installed on your computer as part of your Bash install (described above).
*** Mac OS X
For OS X 10.9 and higher, install Git for Mac by downloading and running [[http://git-scm.com/downloads][the installer]]. After installing Git, there will not be anything in your =/Applications=, 	as Git is a command line program.

For older versions of OS X (10.6-10.8) use the most recent available installer for your
OS [[http://sourceforge.net/projects/git-osx-installer/files/][available here]]. Use the Leopard installer for 10.5 and the Snow Leopard installer for 10.6-10.8.
*** Linux
If Git is not already available on your machine you can try to install it via your distro's package manager. For Debian/Ubuntu run =sudo apt-get install git= and for Fedora run =sudo yum install git=.
** R
[[http://www.r-project.org][R]] is a programming language that is especially powerful for data exploration, visualization, and statistical analysis. To interact with R, we'll use [[http://www.rstudio.com/][RStudio]].
*** Windows 
Install R by downloading and running [[http://cran.r-project.org/bin/windows/base/release.htm][this .exe file]] [[http://cran.r-project.org/index.html][CRAN]]. Also, please install the  [[http://www.rstudio.com/ide/download/desktop][RStudio IDE]].
*** Mac OS X
Install R by downloading and running [[http://cran.r-project.org/bin/macosx/R-latest.pkg][this .pkg file]] [[http://cran.r-project.org/index.html][CRAN]]. Also, please install the
[[http://www.rstudio.com/ide/download/desktop][RStudio IDE]].
*** Linux
You can download the binary files for your distribution from [[http://cran.r-project.org/index.html][CRAN]]. Or
you can use your package manager (e.g. for Debian/Ubuntu 	run =sudo apt-get install r-base= and for Fedora run =sudo yum install R=.  Also, please install the [[href=http://www.rstudio.com/ide/download/desktop][RStudio IDE]].
* Course Materials
- Etherpad: we'll use this etherpad to share notes and code: https://etherpad.mozilla.org/2015-05-13-rr-workshop
- [[file:lectures/reproducible-research-workshop.org][Lecture notes]]
* External resources
** R and RStudio
- [[http://www.rstudio.com/][RStudio]]

** git 
- [[https://try.github.io][GitHub learn git tutorial]]
- [[http://library.ttu.edu/lynda/][TTU lynda.com git tutorial]]
- [[http://blogs.biomedcentral.com/bmcblog/2013/02/28/version-control-for-scientific-research/][BioMed Central post on using verison control in science]]
** Markdown
- [[http://pandoc.org/][pandoc]]



